### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

### ISSUE THREAD

**Issue by zzhdbw** [huggingface/open-r1#129]
when i run the script:
`

export CUDA_VISIBLE_DEVICES=4,5

accelerate launch --config_file configs/zero3.yaml --num_processes=1 src/open_r1/grpo.py \
    --output_dir data/DeepSeek-R1-Distill-Qwen-1.5B-GRPO \
    --model_name_or_path data/Qwen2.5-1.5B-Open-R1-Distill \
    --dataset_name AI-MO/NuminaMath-TIR \
    --max_prompt_length 512 \
    --max_completion_length 1024 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --logging_steps 10 \
    --bf16 \
    --use_vllm \
    --vllm_device auto \
    --vllm_gpu_memory_utilization 0.5`

there is an error:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
[rank0]:[W131 00:24:34.008660282 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0131 00:24:37.750000 1226456 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 1226690) of binary: /home/zzh/miniforge3/envs/open-r1/bin/python3.11`

I think it caused by the  train model in device 4 and vllm infer in device 5. but huow can i fix it?
look forward to your reply!

**Comment by zzhdbw** [comment]
supplement:
now i think its vllm problem:

`[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zzh/code/LLM/open-r1/src/open_r1/grpo.py", line 157, in <module>
[rank0]:     main(script_args, training_args, model_args)
[rank0]:   File "/home/zzh/code/LLM/open-r1/src/open_r1/grpo.py", line 131, in main
[rank0]:     trainer = GRPOTrainer(
[rank0]:               ^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/trl/trainer/grpo_trainer.py", line 313, in __init__
[rank0]:     self.llm = LLM(
[rank0]:                ^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/utils.py", line 986, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 230, in __init__
[rank0]:     self.llm_engine = self.engine_class.from_engine_args(
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 517, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 276, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 429, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 83, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/worker/worker.py", line 275, in initialize_cache
[rank0]:     self._warm_up_model()
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/worker/worker.py", line 291, in _warm_up_model
[rank0]:     self.model_runner.capture_model(self.gpu_cache)
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1525, in capture_model
[rank0]:     graph_runner.capture(**capture_inputs)
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1875, in capture
[rank0]:     self.model(
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 477, in forward
[rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 168, in __call__
[rank0]:     return self.forward(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 332, in forward
[rank0]:     hidden_states = self.get_input_embeddings(input_ids)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 317, in get_input_embeddings
[rank0]:     return self.embed_tokens(input_ids)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 413, in forward
[rank0]:     output_parallel = self.linear_method.embedding(self,
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 45, in embedding
[rank0]:     return F.embedding(input_, layer.weight)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/nn/functional.py", line 2551, in embedding
[rank0]:     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
[rank0]:[W131 00:51:50.005080108 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0131 00:51:53.753000 1247412 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 1247650) of binary: /home/zzh/miniforge3/envs/open-r1/bin/python3.11
Traceback (most recent call last):
  File "/home/zzh/miniforge3/envs/open-r1/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1157, in launch_command
    deepspeed_launcher(args)
  File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/accelerate/commands/launch.py", line 845, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zzh/miniforge3/envs/open-r1/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(`

**Comment by qgallouedec** [comment]
Thanks for reporting. I'm not able to reproduce the issue.

```
# 8 GPUs
export CUDA_VISIBLE_DEVICES=4,5
accelerate launch --config_file configs/zero3.yaml --num_processes=1 src/open_r1/grpo.py --output_dir Qwen2.5-0.5B-GRPO --model_name_or_path Qwen/Qwen2.5-0.5B --dataset_name AI-MO/NuminaMath-TIR --max_prompt_length 512 --max_completion_length 1024 --per_device_train_batch_size 1 --gradient_accumulation_steps 16 --logging_steps 10 --bf16 --use_vllm --vllm_device auto --vllm_gpu_memory_utilization 0.5
```
works here.

Just to be sure: here you're using deepspeed ZeRO 3 with only one GPU for training?

**Comment by Some-random** [comment]
I'm also having the same issue! @qgallouedec I think your command only uses one process

**Comment by Some-random** [comment]
I think I've found a solution. There was a [commit](https://github.com/huggingface/open-r1/commit/c0b53fae290fcac46a690e8fa7965c45093f39b4) yesterday bumping vllm to 0.7.0 but the readme still says 0.6.6.post1. After installing vllm 0.7.0, this particular error disappeared.

I've made a PR for it https://github.com/huggingface/open-r1/pull/132

**Comment by zzhdbw** [comment]
> I think I've found a solution. There was a [commit](https://github.com/huggingface/open-r1/commit/c0b53fae290fcac46a690e8fa7965c45093f39b4) yesterday bumping vllm to 0.7.0 but the readme still says 0.6.6.post1. After installing vllm 0.7.0, this particular error disappeared.我想我已经找到了一个解决方案。昨天有一个[提交](https://github.com/huggingface/open-r1/commit/c0b53fae290fcac46a690e8fa7965c45093f39b4)将 vllm 升级到 0.7.0，但自述文件仍然显示 0.6.6.post1。安装 vllm 0.7.0 后，这个特定错误消失了。
> 
> I've made a PR for it [#132](https://github.com/huggingface/open-r1/pull/132)我已经为它 [#132](https://github.com/huggingface/open-r1/pull/132) 做了一个 PR

Thank you !
