### ISSUE TITLE
System memory usage sudden increase at a particularly step, which leads to memory overflow

### ISSUE THREAD

**Issue by HuiyuanYan** [huggingface/open-r1#496]
I have already posted this issue in the `trl` repository(https://github.com/huggingface/trl/issues/3039). I'm posting it here as well to reach a broader audience and seek more help.

### Reproduction

When using the `GRPOTrainer` in Open-R1 for training, I initially encountered an unexplained timeout error caused by enabling NCCL's peer-to-peer (P2P) communication. To resolve this, I set `NCCL_P2P_DISABLE=1.`

However, during training, I observed that the training process ran smoothly initially, but at a certain step, one of the processes would experience a sudden spike in system memory usage (similar to a memory leak). This caused the system to kill the process, leading to the termination of the training.

I have run the experiment multiple times, and the occurrence of the memory spike seems to be random in terms of when it happens during the training process. It is also possible that a specific data point in the dataset might be causing this issue, but I am not certain about this.

To better identify the root cause, I have added debug output statements at specific locations within the `GRPOTrainer ` code. For example:

```python
# check if all ranks move model to vllm successfully
print(f"INFO: rank[{self.accelerator.process_index}] moving model to vllm")
state_dict = unwrapped_model.state_dict()
print(f"INFO: rank[{self.accelerator.process_index}] finished moving model to vllm")
```
and

```python
# check if all ranks gather rewards successfully
print(f"INFO rank [{self.accelerator.process_index}] gathering rewards...")
rewards_per_func = gather(rewards_per_func)
print(f"INFO rank [{self.accelerator.process_index}] rewards gathered.")
```

Then, in a failed experiment run, I got output like(I used the `nohup` command to run the training in the background.):

```
INFO rank [5] gathering rewards...
INFO rank [5] rewards gathered.

INFO rank [2] gathering rewards...
INFO rank [2] rewards gathered.

INFO rank [4] gathering rewards...
INFO rank [4] rewards gathered.

INFO rank [3] gathering rewards...
INFO rank [3] rewards gathered.

INFO rank [0] gathering rewards...
INFO rank [0] rewards gathered.
W0309 15:22:58.034000 1810248 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1810923 closing signal SIGTERM
W0309 15:22:58.041000 1810248 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1810926 closing signal SIGTERM
W0309 15:22:58.042000 1810248 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1810927 closing signal SIGTERM
W0309 15:22:58.043000 1810248 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1810929 closing signal SIGTERM
W0309 15:22:58.044000 1810248 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1810930 closing signal SIGTERM
E0309 15:23:01.062000 1810248 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -9) local_rank: 1 (pid: 1810925) of binary: /home/yanhuiyuan/anaconda3/envs/openr1/bin/python
Traceback (most recent call last):
  File "/home/yanhuiyuan/anaconda3/envs/openr1/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yanhuiyuan/anaconda3/envs/openr1/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/yanhuiyuan/anaconda3/envs/openr1/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1182, in launch_command
    deepspeed_launcher(args)
  File "/home/yanhuiyuan/anaconda3/envs/openr1/lib/python3.11/site-packages/accelerate/commands/launch.py", line 861, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/yanhuiyuan/anaconda3/envs/openr1/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/yanhuiyuan/anaconda3/envs/openr1/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanhuiyuan/anaconda3/envs/openr1/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
src/open_r1/grpo.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-09_15:22:58
  host      : registry.local
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 1810925)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 1810925
========================================================
```

Then I used command `dmesg | egrep -i -B100 'killed process'` to check why it was killed:
```
[4485632.090139] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0-1,global_oom,task_memcg=/user.slice/user-1006.slice/session-3396.scope,task=python,pid=1810925,uid=1006
[4485632.090324] Out of memory: Killed process 1810925 (python) total-vm:1093703036kB, anon-rss:978285020kB, file-rss:81700kB, shmem-rss:249880kB, UID:1006 pgtables:1940652kB oom_score_adj:0
``` 

I also checked the system usage on `wandb`. The table `System Memory Utilization` shows like:

![Image](https://github.com/user-attachments/assets/e6277294-2187-4dc9-b3b5-c6b591f153ef)

In another run, the situation seems like the same but `oom` in a different step with different running time:

![Image](https://github.com/user-attachments/assets/262daee5-643b-482e-8fa6-b17476d134e7)

I used 7*`A100`  80 GB GPU, 1 for vllm, 6 for training process.

My trainging config:
```yaml
# Model arguments
model_name_or_path: /data1/yanhuiyuan/models/Qwen2.5-Math-7B-TACO
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: pxyyy/NuminaMath-CoT-smp10k
dataset_configs:
- default

# wandb project
wandb_entity: my_entity
wandb_project: Qwen2.5-Math-7B-GRPO

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.6
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

learning_rate: 1.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
max_prompt_length: 1024
max_completion_length: 2048 # 2048(completion) + 512(prompt) + 512(code output)
max_steps: -1
num_generations: 8
num_train_epochs: 1
output_dir: /data1/yanhuiyuan/models/Qwen2.5-Math-7B-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- wandb
reward_funcs:
- my_reward1
- my_reward2
reward_weights:
- 1.0
- 1.0
save_strategy: "steps"
save_steps: 200

seed: 42
temperature: 0.7
warmup_ratio: 0.1
```

My accelerate config:
```
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

My `python` virtual env:
```
absl-py                           2.1.0
accelerate                        1.4.0
aenum                             3.1.15
aiohappyeyeballs                  2.4.6
aiohttp                           3.11.12
aiohttp-cors                      0.7.0
aiosignal                         1.3.2
airportsdata                      20250224
annotated-types                   0.7.0
antlr4-python3-runtime            4.13.2
anyio                             4.8.0
astor                             0.8.1
attrs                             25.1.0
bitsandbytes                      0.45.2
blake3                            1.0.4
blis                              0.7.11
cachetools                        5.5.2
catalogue                         2.0.10
certifi                           2025.1.31
chardet                           5.2.0
charset-normalizer                3.4.1
click                             8.1.8
cloudpathlib                      0.16.0
cloudpickle                       3.1.1
colorama                          0.4.6
colorful                          0.5.6
colorlog                          6.9.0
compressed-tensors                0.9.1
confection                        0.1.5
cos-python-sdk-v5                 1.9.34
crcmod                            1.7
cymem                             2.0.11
DataProperty                      1.1.0
datasets                          3.3.1
deepspeed                         0.15.4
depyf                             0.18.0
dill                              0.3.8
diskcache                         5.6.3
distlib                           0.3.9
distro                            1.9.0
docker-pycreds                    0.4.0
e2b                               1.1.0
e2b-code-interpreter              1.0.5
einops                            0.8.1
fastapi                           0.115.8
filelock                          3.17.0
flake8                            7.1.2
flash_attn                        2.7.4.post1
frozenlist                        1.5.0
fsspec                            2024.12.0
gguf                              0.10.0
gitdb                             4.0.12
GitPython                         3.1.44
google-api-core                   2.24.1
google-auth                       2.38.0
googleapis-common-protos          1.68.0
grpcio                            1.70.0
h11                               0.14.0
hf_transfer                       0.1.9
hjson                             3.1.0
httpcore                          1.0.7
httptools                         0.6.4
httpx                             0.28.1
huggingface-hub                   0.28.1
idna                              3.10
importlib_metadata                8.6.1
iniconfig                         2.0.0
inquirerpy                        0.3.4
interegular                       0.3.3
isort                             6.0.0
Jinja2                            3.1.5
jiter                             0.8.2
joblib                            1.4.2
jsonschema                        4.23.0
jsonschema-specifications         2024.10.1
langcodes                         3.5.0
langdetect                        1.0.9
language_data                     1.3.0
lark                              1.2.2
latex2sympy2_extended             1.0.6
liger_kernel                      0.5.3
lighteval                         0.6.0.dev0
lm-format-enforcer                0.10.11
lxml                              5.3.1
marisa-trie                       1.2.1
Markdown                          3.7
markdown-it-py                    3.0.0
MarkupSafe                        3.0.2
math-verify                       0.5.2
mbstrdecoder                      1.1.4
mccabe                            0.7.0
mdurl                             0.1.2
mistral_common                    1.5.3
mpmath                            1.3.0
msgpack                           1.1.0
msgspec                           0.19.0
multidict                         6.1.0
multiprocess                      0.70.16
murmurhash                        1.0.12
nest-asyncio                      1.6.0
networkx                          3.4.2
ninja                             1.11.1.3
nltk                              3.9.1
numpy                             1.26.4
nvidia-cublas-cu12                12.4.5.8
nvidia-cuda-cupti-cu12            12.4.127
nvidia-cuda-nvrtc-cu12            12.4.127
nvidia-cuda-runtime-cu12          12.4.127
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.2.1.3
nvidia-curand-cu12                10.3.5.147
nvidia-cusolver-cu12              11.6.1.9
nvidia-cusparse-cu12              12.3.1.170
nvidia-ml-py                      12.570.86
nvidia-nccl-cu12                  2.21.5
nvidia-nvjitlink-cu12             12.4.127
nvidia-nvtx-cu12                  12.4.127
open-r1                           0.1.0.dev0    /data1/yanhuiyuan/workspace/open-r1/src
openai                            1.64.0
opencensus                        0.11.4
opencensus-context                0.1.3
opencv-python-headless            4.11.0.86
outlines                          0.1.11
outlines_core                     0.1.26
packaging                         24.2
pandas                            2.2.3
parameterized                     0.9.0
partial-json-parser               0.2.1.1.post5
pathvalidate                      3.2.3
peewee                            3.17.9
pfzy                              0.3.4
pillow                            11.1.0
pip                               25.0.1
platformdirs                      4.3.6
pluggy                            1.5.0
portalocker                       3.1.1
preshed                           3.0.9
prometheus_client                 0.21.1
prometheus-fastapi-instrumentator 7.0.2
prompt_toolkit                    3.0.50
propcache                         0.2.1
proto-plus                        1.26.0
protobuf                          3.20.3
psutil                            7.0.0
py-cpuinfo                        9.0.0
py-spy                            0.4.0
pyarrow                           19.0.1
pyasn1                            0.6.1
pyasn1_modules                    0.4.1
pycodestyle                       2.12.1
pycountry                         24.6.1
pycryptodome                      3.21.0
pydantic                          2.10.6
pydantic_core                     2.27.2
pyflakes                          3.2.0
Pygments                          2.19.1
pynvml                            12.0.0
pytablewriter                     1.2.1
pytest                            8.3.4
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
pytz                              2025.1
PyYAML                            6.0.2
pyzmq                             26.2.1
ray                               2.42.1
referencing                       0.36.2
regex                             2024.11.6
requests                          2.32.3
rich                              13.9.4
rouge_score                       0.1.2
rpds-py                           0.23.1
rsa                               4.9
ruff                              0.9.6
sacrebleu                         2.5.1
safetensors                       0.5.2
scikit-learn                      1.6.1
scipy                             1.15.2
sentencepiece                     0.2.0
sentry-sdk                        2.22.0
setproctitle                      1.3.5
setuptools                        75.8.0
six                               1.17.0
smart-open                        6.4.0
smmap                             5.0.2
sniffio                           1.3.1
spacy                             3.7.2
spacy-legacy                      3.0.12
spacy-loggers                     1.0.5
srsly                             2.5.1
starlette                         0.45.3
swanboard                         0.1.7b1
swankit                           0.1.3
swanlab                           0.4.9
sympy                             1.13.1
tabledata                         1.3.4
tabulate                          0.9.0
tcolorpy                          0.1.7
tensorboard                       2.19.0
tensorboard-data-server           0.7.2
termcolor                         2.3.0
thinc                             8.2.5
threadpoolctl                     3.5.0
tiktoken                          0.9.0
tokenizers                        0.21.0
torch                             2.5.1
torchaudio                        2.5.1
torchvision                       0.20.1
tqdm                              4.67.1
transformers                      4.49.0
triton                            3.1.0
trl                               0.16.0.dev0
typepy                            1.3.4
typer                             0.9.4
typing_extensions                 4.12.2
tzdata                            2025.1
ujson                             5.10.0
urllib3                           2.3.0
uvicorn                           0.34.0
uvloop                            0.21.0
virtualenv                        20.29.2
vllm                              0.7.2
wandb                             0.19.7
wasabi                            1.1.3
watchfiles                        1.0.4
wcwidth                           0.2.13
weasel                            0.3.4
websockets                        15.0
Werkzeug                          3.1.3
wheel                             0.45.1
xformers                          0.0.28.post3
xgrammar                          0.1.14
xmltodict                         0.14.2
xxhash                            3.5.0
yarl                              1.18.3
zipp                              3.21.0
```

I use command `NCCL_P2P_DISABLE=1 NCCL_P2P_LEVEL=NVL NCCL_DEBUG=INFO TORCH_DISTRIBUTED_DEBUG=INFO CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 ACCELERATE_LOG_LEVEL=info nohup accelerate launch --config_file recipes/accelerate_configs/zero3.yaml --num_processes=6 src/open_r1/grpo.py --config recipes/Qwen2.5-Math-7B/grpo/my_config.yaml > train.log 2>&1 &` to start training.

It's really wired and I hope to get everyone's help! :)

### System Info

[2025-03-10 11:57:14,872] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
INFO 03-10 11:57:16 __init__.py:190] Automatically detected platform cuda.

Copy-paste the following information when reporting an issue:

- Platform: Linux-5.15.0-127-generic-x86_64-with-glibc2.31
- Python version: 3.11.11
- PyTorch version: 2.5.1
- CUDA device(s): NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB
- Transformers version: 4.49.0
- Accelerate version: 1.4.0
- Accelerate config: not found
- Datasets version: 3.3.1
- HF Hub version: 0.28.1
- TRL version: 0.16.0.dev0
- bitsandbytes version: 0.45.2
- DeepSpeed version: 0.15.4
- Diffusers version: not installed
- Liger-Kernel version: 0.5.3
- LLM-Blender version: not installed
- OpenAI version: 1.64.0
- PEFT version: not installed

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by HuiyuanYan** [comment]
Okey guys, I found that the reason for this error was that when I was running the code generated by the model (I asked the model to reply with code output), I allowed the code to run on the server without strictly isolating the code environment, resulting in a memory leak. After I changed the code execution environment to `e2b` (as mentioned in the `README`), this issue was resolved.
